window.VOLEI_CONFIG = Object.freeze({
  APP_NAME: 'Sorteio de Duplas de Vôlei',
  API_BASE: 'https://script.google.com/macros/s/AKfycbwxiWDeoeSz-pbI2W8f1AlGKFhS9Xn6A4_Svt5s66wQPdv4khfJeBQWT9WF13sEqt6c/exec',
  SHEET_ID: '1lg0HKljL93wD5riajKbCYcShzKYW0qAVYkPTwjerVAo',
  SHEET_URL: 'https://docs.google.com/spreadsheets/d/1lg0HKljL93wD5riajKbCYcShzKYW0qAVYkPTwjerVAo/edit',
  TABLE_TENNIS_URL: 'https://portalsimonsports.github.io/sorteio-volei/tenis-mesa.html',
  TABLE_TENNIS_ADMIN_URL: 'https://portalsimonsports.github.io/sorteio-volei/tenis-mesa-admin.html',
  DEMO_MODE: false,
  POLL_INTERVAL_MS: 5000,
  BEST_OF_SETS: 3,
  SETS_TO_WIN: 2,
  NORMAL_SET_POINTS: 25,
  TIEBREAK_SET_POINTS: 15,
  MINIMUM_LEAD: 2,
  MATCH_INTERVAL_MINUTES: 10,
  COUNTDOWN_SECONDS: 120,
  THIRD_PLACE_MATCH: true,
  PUBLIC_SHOW_WEIGHTS: false,
  EVENT_TIMEZONE: 'America/Sao_Paulo',
  EVENT_LOCATION: 'Jatobá — Alto Alegre/SP',
  EVENT_DATE: '2026-07-22',
  REGISTRATION_CLOSE_TIME: '10:45',
  COUNTDOWN_START_TIME: '10:48',
  FIRST_MATCH_TIME: '10:50',
  RATING_MIN: 5,
  RATING_MAX: 10,
  RATING_QUESTION: 'Como você avalia o seu jogo?',
  RATING_ADJUSTMENTS: Object.freeze({ 5: 3, 6: 2, 7: 1 }),
  RATING_EXACT_SUFFIX: '*',
  WEATHER_LATITUDE: -21.62488,
  WEATHER_LONGITUDE: -50.24251,
  CHAMPIONSHIP_HISTORY: true,
  CHAMPIONSHIP_REUSE_TEAMS: true,
  HISTORICAL_INDEX: true,
  BALANCED_SEEDING: true,
  PRESERVE_OPERATIONAL_DATA: true,
  TABLE_TENNIS_DEFAULTS: Object.freeze({ BEST_OF: 3, SET_POINTS: 11, MINIMUM_LEAD: 2, WIN_POINTS: 3, LOSS_POINTS: 0, AUTO_START_NEXT: true }),
  VERSION: 'V021_TENIS_MESA_2026-07-23'
});
